spring:
  profiles:
    active: local

security:
  jwt:
    secret: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb
  internal:
    token: YWhnamZrU0lqZWpmamZJU2pkaWZrbHdxcHE=

integration:
  f5-ai:
    key: ZXlKMGVYQWlPaUpLVjFRaUxDSnFkR2tpT2lJMk4yUTJNamMzTTJFeU9UZzVOakV3TkRBd05tUTRZV1FpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUkyTjJRMk1qYzNNMkV5T1RnNU5qRXdOREF3Tm1RNFlXUWlMQ0poWTJOdmRXNTBYMmxrSWpvek9UUXhMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwyRndjQzVtTldGcExuSjFJaXdpWVhWa0lqb2lhSFIwY0hNNkx5OWhjR2t1WmpWaGFTNXlkU0lzSW1saGRDSTZNVGMwTWpBNE9EQTFNU3dpYm1KbUlqb3hOelF5TURnNE1EVXhMQ0oyWlc1a2IzSWlPaUp2Y0dWdVlXa2lMQ0p6WTI5d1pYTWlPbHNpWTJoaGRITWlYWDAublJuYWJxdnFFYUlJSmE3Z0dhaDRYRS1BalFRNWk2N1M3YzJObHVad0FyZwo=
    url: https://api.f5ai.ru/v1/chat/completions
  bmstu:
    host: https://bmstu.ru
    api-url: https://api.www.bmstu.ru/
    events-url: events
    news-url: news
    url-params:
      actual-events: isActual=
      limit: limit=
      offset: offset=
  s3:
    key-id: WUNBSkVISGkycUxwSnRCaTJPTXFFU3FSNg==
    secret-key: WUNQWlBjd2xfQndWQndaelFHclRlcVc1MHhubjBJd0hoT180VEpRUQ==
    region: ru-central1
    s3-endpoint: https://storage.yandexcloud.net
    bucket-name: afishabmstu
    package-name: eventPictures/