server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-main}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

security:
  jwt:
    secret: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb

integration:
  f5-ai:
    key: eyJ0eXAiOiJKV1QiLCJqdGkiOiI2N2Q2Mjc3M2EyOTg5NjEwNDAwNmQ4YWQiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2N2Q2Mjc3M2EyOTg5NjEwNDAwNmQ4YWQiLCJhY2NvdW50X2lkIjozOTQxLCJpc3MiOiJodHRwczovL2FwcC5mNWFpLnJ1IiwiYXVkIjoiaHR0cHM6Ly9hcGkuZjVhaS5ydSIsImlhdCI6MTc0MjA4ODA1MSwibmJmIjoxNzQyMDg4MDUxLCJ2ZW5kb3IiOiJvcGVuYWkiLCJzY29wZXMiOlsiY2hhdHMiXX0.nRnabqvqEaIIJa7gGah4XE-AjQQ5i67S7c2NluZwArg
    url: https://api.f5ai.ru/v1/chat/completions
  bmstu:
    host: https://bmstu.ru
    api-url: https://api.www.bmstu.ru/
    events-url: events
    news-url: news
    url-params:
      actual-events: isActual=
      limit: limit=
      offset: offset=
  s3:
    key-id: YCAJEHHi2qLpJtBi2OMqESqR6
    secret-key: YCPZPcwl_BwVBwZzQGrTeqW50xnn0IwHhO_4TJQQ
    region: ru-central1
    s3-endpoint: https://storage.yandexcloud.net
    bucket-name: afishabmstu
    package-name: eventPictures/